name: qgis
version: 2.18.9
summary: A Free and Open Source Geographic Information System
description: |
  Create, edit, visualise, analyse and publish geospatial information.
  QGIS feels snappy to use and has a pleasing, easy to use graphical user
  interface. It supports a number of raster and vector data formats, with new
  support easily added using the plugin architectur

grade: devel
confinement: strict
architectures: [amd64]

apps:
  qgis:
    command: desktop-launch qgis
    plugs: [home, network, unity7, x11]
    environment:
      GDAL_DATA: $SNAP/usr/share/gdal/1.11

parts:
  qgis:
    source: https://github.com/qgis/QGIS/archive/final-2_18_9.tar.gz
    plugin: cmake
    after: [python-deps, desktop-qt4]
    build-packages:
      - build-essential
      - cmake
      - qt4-default
      - libqtwebkit-dev
      - libqjson-dev
      - python-sip-dev
      - python-qt4-dev
      - python-qscintilla2
      - pyqt4-dev-tools
      - grass-dev
      - libproj-dev
      - libgeos++-dev
      - libgdal-dev
      - libexpat1-dev
      - libsqlite3-dev
      - libqt4-dev
      - libqt4-sql
      - libqt4-sql-sqlite
      - libspatialite-dev
      - libgsl-dev
      - txt2tags
      - libqscintilla2-dev
      - libqwt-dev
      - libspatialindex-dev
      - libqca2-dev
      - libqca2-plugins
    stage-packages:
      - libqt4-sql-sqlite
      - libqca2-plugins
    organize:
      usr/lib/x86_64-linux-gnu/qca/crypto/: usr/lib/x86_64-linux-gnu/qt4/plugins/crypto/
    stage:
      - -include/
      - -usr/share/doc

  python-deps:
    plugin: nil
    stage-packages:
      - python-qt4
      - python-qt4-sql
      - python-sip
      - python-psycopg2
      - python-qscintilla2
      - python-httplib2
      - python-jinja2
      - python-pygments
      - python-requests
      - python-tz
      - python-pyproj
      - python-six
      - python-pyspatialite
      - python-future
      - python-markupsafe
      - python-dateutil
      - python-yaml
      - python-owslib
      - python-gdal
      - python-matplotlib
      - python-shapely

